spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    username: spring_user
    url: jdbc:postgresql://localhost/buumba
  application:
    name: ai-test
  ai:
    ollama:
      chat:
        model: gemma3:4b
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
